# Generated by Django 4.1 on 2022-09-03 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('concert', '0003_concert_image_alter_concert_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valueofcharacteristic',
            name='concerts',
        ),
        migrations.RemoveField(
            model_name='valueofcharacteristic',
            name='type_characteristic',
        ),
        migrations.DeleteModel(
            name='TypeCharacteristic',
        ),
        migrations.DeleteModel(
            name='ValueOfCharacteristic',
        ),
    ]
