# Generated by Django 4.1 on 2022-09-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0004_remove_valueofcharacteristic_concerts_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concert",
            name="description",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="concert",
            name="image",
            field=models.ImageField(upload_to="concert_images"),
        ),
    ]
