# Generated by Django 4.1 on 2022-10-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="purchase_type",
            field=models.CharField(
                choices=[
                    ("RES", "Reserve"),
                    ("BUY", "Buy"),
                    ("CND", "Cancelled"),
                    ("EXP", "Expired"),
                ],
                default="RES",
                max_length=3,
            ),
        ),
    ]
