# Generated by Django 4.1 on 2022-12-18 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("concert", "0006_alter_concert_description"),
        ("order", "0002_alter_order_purchase_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="concert",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="concert.concert",
            ),
        ),
    ]
