# Generated by Django 4.1 on 2022-12-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_concert"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="concert",
            field=models.IntegerField(),
        ),
    ]
